# Generated by Django 4.2 on 2023-04-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cadastro_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
